IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'VeMayBay')
BEGIN
    CREATE DATABASE [VeMayBay];
END;
GO

USE VeMayBay;
GO

IF OBJECT_ID('dbo.Seats', 'U') IS NOT NULL
    DROP TABLE dbo.Seats;
GO

CREATE TABLE dbo.Seats (
	SeatId INT IDENTITY(1,1) PRIMARY KEY,
	SeatNumber VARCHAR(10) UNIQUE NOT NULL,
	Status VARCHAR(10) NOT NULL CHECK (status IN ('AVAILABLE', 'HELD', 'BOOKED')),
    HoldExpiresAt DATETIME NULL,
    HeldByPhone VARCHAR(20) NULL
);
GO

INSERT INTO dbo.Seats
	(SeatNumber, Status, HoldExpiresAt, HeldByPhone)
VALUES
	(1, 'AVAILABLE', NULL, NULL),
	(2, 'AVAILABLE', NULL, NULL),
	(3, 'AVAILABLE', NULL, NULL),
	(4, 'AVAILABLE', NULL, NULL),
	(5, 'AVAILABLE', NULL, NULL),
	(6, 'AVAILABLE', NULL, NULL),
	(7, 'AVAILABLE', NULL, NULL),
	(8, 'AVAILABLE', NULL, NULL),
	(9, 'AVAILABLE', NULL, NULL),
	(10, 'AVAILABLE', NULL, NULL),
	(11, 'AVAILABLE', NULL, NULL),
	(12, 'AVAILABLE', NULL, NULL),
	(13, 'AVAILABLE', NULL, NULL),
	(14, 'AVAILABLE', NULL, NULL),
	(15, 'AVAILABLE', NULL, NULL),
	(16, 'AVAILABLE', NULL, NULL),
	(17, 'AVAILABLE', NULL, NULL),
	(18, 'AVAILABLE', NULL, NULL),
	(19, 'AVAILABLE', NULL, NULL),
	(20, 'AVAILABLE', NULL, NULL);
GO

SELECT * FROM dbo.Seats;
GO